In [2]:
import numpy as np
import threading 
import os
import time
import queue

## Question: 1

In [ ]:
%%time 
MAX = int(input())
  

def printMatrix(M, rowSize, colSize) :  
      
    for i in range(rowSize) :  
        for j in range(colSize) :  
            print(M[i][j], end = " ") 
  
        print()  
  
def multiplyMatrix(row1, col1, A,  
                   row2, col2, B) : 
                          
     
    C = [[0 for i in range(MAX)]  
            for j in range(MAX)] 
  
  
    if (row2 != col1) : 
        print("Not Possible") 
        return
      
    # Multiply the two  
    for i in range(row1) : 
        for j in range(col2) : 
            C[i][j] = 0
            for k in range(row2) : 
                C[i][j] += A[i][k] * B[k][j];  
  
    # Print the result  
    print("Resultant Matrix: ") 
    printMatrix(C, row1, col2) 
  
# Driver Code 
if __name__ == "__main__" : 
  
    A = [[0 for i in range(MAX)]  
            for j in range(MAX)] 
    B = [[0 for i in range(MAX)]  
            for j in range(MAX)] 
  
    # Read size of Matrix A from user  
    n=int(input())
    row1 =n
    col1 =n 
  
    # Read the elements of Matrix A from user  
    print("Enter the elements of First Matrix: ");  
    for i in range(row1) :  
        for j in range(col1) :  
            A[i][j] = int(input("A[" + str(i) +
                                "][" + str(j) + "]: ")) 
 
    row2 = n
    col2 = n
    # Read the elements of Matrix B from user  
    print("Enter the elements of Second Matrix: ");  
    for i in range(row2) :  
        for j in range(col2) : 
            B[i][j] = int(input("B[" + str(i) +
                                "][" + str(j) + "]: ")) 
  
    # Print the Matrix A  
    print("First Matrix: ") 
    printMatrix(A, row1, col1) 
  
    # Print the Matrix B  
    print("Second Matrix: ") 
    printMatrix(B, row2, col2) 
  
    # Find the product of the 2 matrices  
    multiplyMatrix(row1, col1, A, row2, col2, B)

using multithreading

In [ ]:
%%time
import threading 
import os
import numpy as np 
n=int(input())
A = [[0 for i in range()]  
            for j in range(n)] 
B = [[0 for i in range(n)]  
            for j in range(n)]
print("Enter the elements of First Matrix: ")  
for i in range(n) :  
    for j in range(n) :  
            A[i][j] = int(input("A[" + str(i) +
                                "][" + str(j) + "]: "))
print("Enter the elements of First Matrix: ")  
for i in range(n) :  
      for j in range(n) :  
            B[i][j] = int(input("B[" + str(i) +
                                "][" + str(j) + "]: "))           
def fun(mat1, mat2, fin, i):
  for j in range(n):
    for k in range(n):
      fin[i][j] += mat1[i][k] * mat2[k][j]


threads = [None]*n
fin = np.zeros((n,n))

for i in range(n):
  threads[i] = threading.Thread(target = fun, args = (A, B, fin, i))
  threads[i].start()

for i in range(n):
  threads[i].join()

print(fin)


 numpy matrix multiplication.

In [7]:
%%time
size = 99
a = np.random.randint(1,1000,(size,size))
b = np.random.randint(1,1000,(size,size))
result = np.dot(a,b)
print(result)

[[25968837 25409106 25397947 ... 24180794 23438224 26229170]
 [27367268 25620863 25811913 ... 24115211 22414974 28030307]
 [25773555 23030445 24139901 ... 22959576 22226825 25821140]
 ...
 [25039522 25621118 23989460 ... 23831649 21163049 26809956]
 [24962425 21492011 21897568 ... 22376451 21497984 23006214]
 [24170008 25083792 22733071 ... 25447022 22569474 26144357]]
CPU times: user 3.75 ms, sys: 159 µs, total: 3.91 ms
Wall time: 5.63 ms



## Question: 2

without threading


In [8]:
%%time 
arr = list(map(int,input().split()))
arr = np.asarray(arr)
x = int(input())
y = np.where(arr == x)

print(y)

1 2 3 4 5 6 7 89 
5
(array([4]),)
CPU times: user 3.06 ms, sys: 1.66 ms, total: 4.72 ms
Wall time: 22.2 s


Threading

In [13]:
%%time
a = np.random.randint(100,size = 1000000)
l=a.shape[0]
result_t=0
def func_1(arr, c, result_t):
    result_t = []
    for i in range(len(arr)):
        if(c == arr[i]):
            result_t.append(i)
    print(result_t)
def func_2(arr, c,result_t):
    result_t = []
    for i in range(len(arr)):
        if(c == arr[i]):
            result_t.append((l//2)+i)
    print(result_t)

c = 5
threads = [None]*2



threads[0] = threading.Thread(target = func_1, args = (arr[:(l//2)], c, result_t))
threads[0].start()
threads[1] = threading.Thread(target = func_2, args = (arr[(l//2):], c, result_t))
threads[1].start()

for i in range(2):
  threads[i].join()



[16, 53, 107, 162, 355, 390, 738, 1029, 1069, 1104, 1281, 1331, 1389, 1410, 1525, 1726, 1944, 1978, 2046, 2100, 2152, 2261, 2310, 2384, 2570, 2849, 2978, 3119, 3163, 3171, 3209, 3215, 3226, 3353, 3385, 3457, 3505, 3518, 3638, 3657, 3828, 3859, 3994, 4209, 4400, 4436, 4473, 4629, 4644, 4700, 4737, 4855, 4901, 4963, 5065, 5086, 5302, 5443, 5517, 5603, 5625, 6140, 6145, 6377, 6393, 6403, 6758, 6945, 6976, 7091, 7104, 7473, 7507, 7520, 7527, 7702, 7741, 7743, 7835, 8267, 8449, 8514, 8727, 8960, 9027, 9117, 9324, 9512, 9700, 9725, 9997, 10052, 10467, 10510, 11031, 11139, 11229, 11414, 11459, 11874, 11934, 12381, 12456, 12458, 12581, 12646, 12679, 12713, 12794, 12802, 12916, 13066, 13133, 13194, 13250, 13266, 13285, 13447, 13506, 13628, 13629, 13700, 13714, 13726, 14327, 14329, 14376, 14595, 14646, 14764, 15099, 15180, 15230, 15260, 15327, 15349, 15494, 15517, 15598, 15619, 15748, 15822, 15830, 15854, 15883, 15889, 15985, 16008, 16065, 16068, 16097, 16203, 16217, 16232, 16634, 16647, 16663, 

##Question: 3

without multithreading

1.   List item
2.   List item



In [14]:
%%time 
arr = list(map(int,input().split()))
sum=0
for i in range(len(arr)):
  sum=sum+arr[i]
print(sum)


1 2 3 4 5 6 7 8 9 
45
CPU times: user 595 µs, sys: 2.12 ms, total: 2.71 ms
Wall time: 8 s


threading



In [20]:
%%time
a = np.random.randint(100,size = 1000000)
def  sum(a):
    sum = 0
    for i in range(len(a)):
        sum += a[i]
    return sum

qu = queue.Queue()
thread_list = list()

l=a.shape[0]
final_sum = 0

t0 = threading.Thread(target=lambda b, arg1: b.put(sum(arg1)), args=(qu, a[:(l//2)]))
t0.start()
threads_list.append(t0)

t1 = threading.Thread(target=lambda b, arg1: b.put(sum(arg1)), args=(qu, a[(l//2):]))
t1.start()
thread_list.append(t1)

for t in threads_list:
    t.join()

while not qu.empty():
    final_sum += qu.get()
print(final_sum)

49493162
CPU times: user 247 ms, sys: 6.25 ms, total: 253 ms
Wall time: 256 ms


using built-in functions

In [21]:
%%time
a = np.random.randint(100,size = 100000)
a.sum()

CPU times: user 2.19 ms, sys: 0 ns, total: 2.19 ms
Wall time: 1.76 ms


##Question: 4

without multithreading


In [29]:
lo = 1
hi = 10000

In [30]:
res=[]
for num in range(lo, hi + 1):
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           res.append(num)
print(res)

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217,

using threading


In [33]:
%%time

def prime(l0,hi,res):
    result=[]
    for num in range(l0, hi + 1):
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           result.append(num)
    res.put(result)

q = queue.Queue()
thread_list = list()

final_res = []

t = threading.Thread(prime(lo, hi//2, q))
t.start()
thread_list.append(t)

t0 = threading.Thread(prime(hi//2, hi, q))
t0.start()
thread_list.append(t0)

for x in threads_list:
    x.join()

for i in q.queue:
    final_res +=i
print(final_res)

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217,